function autoDetectExamSyllabus(examName) {
  if (!examName || typeof examName !== 'string') return [];
  const normalized = examName.trim().toLowerCase();
  if (normalized === '') return [];
  const syllabus = {
    'sat': ['Reading Comprehension', 'Writing and Language', 'Math - No Calculator', 'Math - Calculator', 'Essay (Optional)'],
    'gre': ['Verbal Reasoning', 'Quantitative Reasoning', 'Analytical Writing', 'Experimental Section'],
    'jee main': ['Physics', 'Chemistry', 'Mathematics'],
    'jee advanced': ['Physics', 'Chemistry', 'Mathematics'],
    'cfa level 1': ['Ethical and Professional Standards', 'Quantitative Methods', 'Economics', 'Financial Reporting and Analysis', 'Corporate Issuers', 'Equity Investments', 'Fixed Income', 'Derivatives', 'Alternative Investments', 'Portfolio Management'],
    'cfa level 2': ['Ethical and Professional Standards', 'Quantitative Methods', 'Economics', 'Financial Reporting and Analysis', 'Corporate Issuers', 'Equity Investments', 'Fixed Income', 'Derivatives', 'Alternative Investments', 'Portfolio Management'],
    'cfa level 3': ['Ethical and Professional Standards', 'Behavioral Finance', 'Economics', 'Asset Allocation', 'Fixed Income', 'Equity Portfolio Management', 'Derivatives', 'Alternative Investments', 'Risk Management', 'Portfolio Execution'],
    'act': ['English', 'Mathematics', 'Reading', 'Science', 'Writing (Optional)'],
    'toefl': ['Reading', 'Listening', 'Speaking', 'Writing'],
    'ielts': ['Listening', 'Reading', 'Writing', 'Speaking'],
    'gmat': ['Analytical Writing Assessment', 'Integrated Reasoning', 'Quantitative', 'Verbal'],
    'lsat': ['Logical Reasoning', 'Analytical Reasoning', 'Reading Comprehension', 'Writing Sample (Unscored)'],
    'mcat': ['Chemical and Physical Foundations of Biological Systems', 'Critical Analysis and Reasoning Skills', 'Biological and Biochemical Foundations of Living Systems', 'Psychological, Social, and Biological Foundations of Behavior'],
    'ap calculus ab': ['Limits and Continuity', 'Differentiation', 'Applications of Differentiation', 'Integration', 'Applications of Integration'],
    'ap calculus bc': ['Limits and Continuity', 'Differentiation', 'Applications of Differentiation', 'Integration', 'Applications of Integration', 'Parametric Equations, Polar Coordinates, and Vector-Valued Functions', 'Infinite Sequences and Series'],
    'ap physics 1': ['Kinematics', 'Dynamics', 'Circular Motion and Gravitation', 'Energy', 'Momentum', 'Simple Harmonic Motion', 'Torque and Rotational Motion', 'Electric Charge and Electric Force', 'DC Circuits', 'Mechanical Waves and Sound'],
    'ap physics 2': ['Fluids', 'Thermodynamics', 'Electric Force, Field, and Potential', 'Electric Circuits', 'Magnetism and Electromagnetic Induction', 'Geometric and Physical Optics', 'Quantum, Atomic, and Nuclear Physics'],
    'ap chemistry': ['Atomic Structure and Properties', 'Molecular and Ionic Compound Structure and Properties', 'Intermolecular Forces and Properties', 'Chemical Reactions', 'Kinetics', 'Thermodynamics', 'Equilibrium', 'Acids and Bases', 'Applications of Thermodynamics'],
    'ap biology': ['Chemistry of Life', 'Cell Structure and Function', 'Cellular Energetics', 'Cell Communication and Cell Cycle', 'Heredity', 'Gene Expression and Regulation', 'Natural Selection', 'Ecology'],
    'ap english language': ['Rhetorical Analysis', 'Argument', 'Synthesis'],
    'ap english literature': ['Poetry Analysis', 'Prose Fiction Analysis', 'Literary Argument'],
    'ap us history': ['Period 1: 1491-1607', 'Period 2: 1607-1754', 'Period 3: 1754-1800', 'Period 4: 1800-1848', 'Period 5: 1844-1877', 'Period 6: 1865-1898', 'Period 7: 1890-1945', 'Period 8: 1945-1980', 'Period 9: 1980-Present'],
    'ap world history': ['The Global Tapestry', 'Networks of Exchange', 'Land-Based Empires', 'Transoceanic Interconnections', 'Revolutions', 'Consequences of Industrialization', 'Global Conflict', 'Cold War and Decolonization', 'Globalization'],
    'ib math aa sl': ['Number and Algebra', 'Functions', 'Geometry and Trigonometry', 'Statistics and Probability', 'Calculus'],
    'ib math aa hl': ['Number and Algebra', 'Functions', 'Geometry and Trigonometry', 'Statistics and Probability', 'Calculus', 'Option: Statistics and Probability or Sets, Relations and Groups or Calculus or Discrete Mathematics'],
    'ib math ai sl': ['Number and Algebra', 'Functions', 'Geometry and Trigonometry', 'Statistics and Probability', 'Calculus'],
    'ib math ai hl': ['Number and Algebra', 'Functions', 'Geometry and Trigonometry', 'Statistics and Probability', 'Calculus', 'Option: Statistics and Probability or Sets, Relations and Groups or Calculus or Discrete Mathematics'],
    'ib physics sl': ['Measurements and Uncertainties', 'Mechanics', 'Thermal Physics', 'Waves', 'Electricity and Magnetism', 'Circular Motion and Gravitation', 'Atomic, Nuclear and Particle Physics', 'Energy Production'],
    'ib physics hl': ['Measurements and Uncertainties', 'Mechanics', 'Thermal Physics', 'Waves', 'Electricity and Magnetism', 'Circular Motion and Gravitation', 'Atomic, Nuclear and Particle Physics', 'Energy Production', 'Wave Phenomena', 'Fields', 'Electromagnetic Induction', 'Quantum and Nuclear Physics'],
    'ib chemistry sl': ['Stoichiometric Relationships', 'Atomic Structure', 'Periodicity', 'Chemical Bonding and Structure', 'Energetics/Thermochemistry', 'Chemical Kinetics', 'Equilibrium', 'Acids and Bases', 'Redox Processes', 'Organic Chemistry', 'Measurement and Data Processing'],
    'ib chemistry hl': ['Stoichiometric Relationships', 'Atomic Structure', 'Periodicity', 'Chemical Bonding and Structure', 'Energetics/Thermochemistry', 'Chemical Kinetics', 'Equilibrium', 'Acids and Bases', 'Redox Processes', 'Organic Chemistry', 'Measurement and Data Processing', 'Atomic Structure (HL)', 'Periodicity (HL)', 'Chemical Bonding and Structure (HL)', 'Energetics/Thermochemistry (HL)', 'Chemical Kinetics (HL)', 'Equilibrium (HL)', 'Acids and Bases (HL)', 'Redox Processes (HL)', 'Organic Chemistry (HL)', 'Measurement and Data Processing (HL)'],
    'ib biology sl': ['Cell Biology', 'Molecular Biology', 'Genetics', 'Ecology', 'Evolution and Biodiversity', 'Human Physiology'],
    'ib biology hl': ['Cell Biology', 'Molecular Biology', 'Genetics', 'Ecology', 'Evolution and Biodiversity', 'Human Physiology', 'Nucleic Acids', 'Metabolism, Cell Respiration and Photosynthesis', 'Plant Biology', 'Genetics and Evolution', 'Animal Physiology'],
    'gate cs': ['Engineering Mathematics', 'Digital Logic', 'Computer Organization and Architecture', 'Programming and Data Structures', 'Algorithms', 'Theory of Computation', 'Compiler Design', 'Operating System', 'Databases', 'Computer Networks'],
    'gate ece': ['Engineering Mathematics', 'Networks, Signals and Systems', 'Electronic Devices', 'Analog Circuits', 'Digital Circuits', 'Control Systems', 'Communications', 'Electromagnetics'],
    'gate me': ['Engineering Mathematics', 'Applied Mechanics and Design', 'Fluid Mechanics and Thermal Sciences', 'Materials, Manufacturing and Industrial Engineering'],
    'neet': ['Physics', 'Chemistry', 'Biology (Botany and Zoology)'],
    'cat': ['Verbal Ability and Reading Comprehension', 'Data Interpretation and Logical Reasoning', 'Quantitative Ability'],
    'xat': ['Verbal and Logical Ability', 'Decision Making', 'Quantitative Ability and Data Interpretation', 'General Knowledge (GK)'],
    'mat': ['Language Comprehension', 'Mathematical Skills', 'Data Analysis and Sufficiency', 'Intelligence and Critical Reasoning', 'Indian and Global Environment'],
    'sbi po': ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Computer Aptitude'],
    'ibps po': ['English Language', 'Quantitative Aptitude', 'Reasoning Ability', 'General Awareness', 'Computer Aptitude'],
    'ssc cgl': ['General Intelligence and Reasoning', 'General Awareness', 'Quantitative Aptitude', 'English Comprehension'],
    'upsc civil services': ['General Studies I', 'General Studies II', 'General Studies III', 'General Studies IV', 'Optional Subject Paper I', 'Optional Subject Paper II'],
    'cbse class 10': ['Mathematics', 'Science', 'Social Science', 'English', 'Hindi'],
    'cbse class 12': ['Physics', 'Chemistry', 'Mathematics', 'Biology', 'English', 'Computer Science', 'Accountancy', 'Business Studies', 'Economics'],
    'icse class 10': ['English Language', 'Literature in English', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'History and Civics', 'Geography', 'Hindi'],
    'icse class 12': ['English', 'Mathematics', 'Physics', 'Chemistry', 'Biology', 'Computer Science', 'Commerce', 'Economics', 'Accountancy'],
    'a level mathematics': ['Pure Mathematics', 'Mechanics', 'Statistics'],
    'a level physics': ['Measurements and their errors', 'Particles and radiation', 'Waves', 'Mechanics and materials', 'Electricity', 'Further mechanics and thermal physics', 'Fields and their consequences', 'Nuclear physics'],
    'a level chemistry': ['Physical chemistry', 'Inorganic chemistry', 'Organic chemistry'],
    'a level biology': ['Biological molecules', 'Cells', 'Organisms exchange substances with their environment', 'Genetic information, variation and relationships between organisms', 'Energy transfers in and between organisms', 'Organisms respond to changes in their internal and external environments', 'Genetics, populations, evolution and ecosystems', 'The control of gene expression'],
    'a level economics': ['Microeconomics', 'Macroeconomics'],
    'a level history': ['Breadth study', 'Depth study', 'Historical investigation'],
    'a level geography': ['Physical geography', 'Human geography', 'Geographical investigation'],
    'a level english literature': ['Poetry', 'Prose', 'Drama', 'Coursework'],
    'a level psychology': ['Social influence', 'Memory', 'Attachment', 'Psychopathology', 'Approaches in psychology', 'Biopsychology', 'Research methods', 'Issues and debates in psychology'],
    'a level sociology': ['Education with theory and methods', 'Families and households', 'Beliefs in society', 'Crime and deviance', 'Theory and methods'],
    'a level business': ['What is business?', 'Managers, leadership and decision making', 'Decision making to improve marketing performance', 'Decision making to improve operational performance', 'Decision making to improve financial performance', 'Decision making to improve human resource performance', 'Analysing the strategic position of a business', 'Choosing strategic direction', 'Strategic methods: how to pursue strategies', 'Managing strategic change'],
    'a level computer science': ['Fundamentals of programming', 'Fundamentals of data structures', 'Fundamentals of algorithms', 'Theory of computation', 'Fundamentals of data representation', 'Fundamentals of computer systems', 'Fundamentals of computer organisation and architecture', 'Consequences of uses of computing', 'Fundamentals of communication and networking', 'Fundamentals of databases', 'Big Data', 'Fundamentals of functional programming', 'Systematic approach to problem solving'],
    'a level law': ['The nature of law and the English legal system', 'Criminal law', 'Tort law', 'Law of contract', 'Human rights law'],
    'a level politics': ['Government and politics of the UK', 'Government and politics of the USA', 'Political ideas'],
    'a level philosophy': ['Epistemology', 'Moral philosophy', 'Metaphysics of God', 'Metaphysics of mind'],
    'a level religious studies': ['Philosophy of religion', 'Religion and ethics', 'Study of religion'],
    'a level music': ['Performing', 'Composing', 'Appraising'],
    'a level art': ['Personal investigation', 'Externally set assignment'],
    'a level drama': ['Devising', 'Text in performance', 'Theatre makers in practice'],
    'a level media studies': ['Media language', 'Media representation', 'Media industries', 'Media audiences'],
    'a level physical education': ['Applied anatomy and physiology', 'Skill acquisition', 'Sport and society', 'Exercise physiology', 'Biomechanical movement', 'Sport psychology'],
    'a level food science': ['Food science and nutrition', 'Food safety', 'Food choice'],
    'a level textiles': ['Fibres and fabrics', 'Textile construction', 'Textile design'],
    'a level product design': ['Materials and components', 'Design and market influences', 'Processes and manufacture'],
    'a level engineering': ['Engineering principles', 'Design and manufacture', 'Systems and control'],
    'a level environmental science': ['The living environment', 'The physical environment', 'Energy resources', 'Pollution', 'Biological resources', 'Sustainability'],
    'a level geology': ['Elements, minerals and rocks', 'Surface and internal processes', 'Geological time', 'Geological hazards'],
    'a level astronomy': ['Planetary systems', 'Stars', 'Galaxies', 'Cosmology'],
    'a level classical civilisation': ['The world of the hero', 'Greek theatre', 'Roman civilisation'],
    'a level ancient history': ['Greek history', 'Roman history'],
    'a level archaeology': ['The archaeology of the British Isles', 'The archaeology of the classical world'],
    'a level history of art': ['Visual analysis', 'Themes in art', 'Art in context'],
    'a level dance': ['Performance', 'Choreography', 'Appreciation'],
    'a level film studies': ['Film form', 'Film meaning', 'Film context'],
    'a level photography': ['Portfolio', 'Externally set assignment'],
    'a level graphic communication': ['Portfolio', 'Externally set assignment'],
    'a level three-dimensional design': ['Portfolio', 'Externally set assignment'],
    'a level fine art': ['Portfolio', 'Externally set assignment'],
    'a level critical and contextual studies': ['Portfolio', 'Externally set assignment'],
    'a level digital media': ['Portfolio', 'Externally set assignment'],
    'a level moving image': ['Portfolio', 'Externally set assignment'],
    'a level sound': ['Portfolio', 'Externally set assignment'],
    'a level interactive media': ['Portfolio', 'Externally set assignment'],
    'a level games design': ['Portfolio', 'Externally set assignment'],
    'a level animation': ['Portfolio', 'Externally set assignment'],
    'a level visual effects': ['Portfolio', 'Externally set assignment'],
    'a level virtual reality': ['Portfolio', 'Externally set assignment'],
    'a level augmented reality': ['Portfolio', 'Externally set assignment'],
    'a level artificial intelligence': ['Portfolio', 'Externally set assignment'],
    'a level machine learning': ['Portfolio', 'Externally set assignment'],
    'a level data science': ['Portfolio', 'Externally set assignment'],
    'a level cyber security': ['Portfolio', 'Externally set assignment'],
    'a level ethical hacking': ['Portfolio', 'Externally set assignment'],
    'a level digital forensics': ['Portfolio', 'Externally set assignment'],
    'a level network security': ['Portfolio', 'Externally set assignment'],
    'a level cloud computing': ['Portfolio', 'Externally set assignment'],
    'a level web development': ['Portfolio', 'Externally set assignment'],
    'a level mobile app development': ['Portfolio', 'Externally set assignment'],
    'a level software engineering': ['Portfolio', 'Externally set assignment'],
    'a level systems analysis': ['Portfolio', 'Externally set assignment'],
    'a level database design': ['Portfolio', 'Externally set assignment'],
    'a level user experience design': ['Portfolio', 'Externally set assignment'],
    'a level user interface design': ['Portfolio', 'Externally set assignment'],
    'a level information technology': ['Portfolio', 'Externally set assignment'],
    'a level computing': ['Portfolio', 'Externally set assignment'],
    'a level ict': ['Portfolio', 'Externally set assignment'],
    'a level digital technology': ['Portfolio', 'Externally set assignment'],
    'a level creative media': ['Portfolio', 'Externally set assignment'],
    'a level media production': ['Portfolio', 'Externally set assignment'],
    'a level journalism': ['Portfolio', 'Externally set assignment'],
    'a level publishing': ['Portfolio', 'Externally set assignment'],
    'a level advertising': ['Portfolio', 'Externally set assignment'],
    'a level marketing': ['Portfolio', 'Externally set assignment'],
    'a level public relations': ['Portfolio', 'Externally set assignment'],
    'a level event management': ['Portfolio', 'Externally set assignment'],
    'a level hospitality': ['Portfolio', 'Externally set assignment'],
    'a level tourism': ['Portfolio', 'Externally set assignment'],
    'a level travel': ['Portfolio', 'Externally set assignment'],
    'a level leisure': ['Portfolio', 'Externally set assignment'],
    'a level sport': ['Portfolio', 'Externally set assignment'],
    'a level exercise science': ['Portfolio', 'Externally set assignment'],
    'a level nutrition': ['Portfolio', 'Externally set assignment'],
    'a level health': ['Portfolio', 'Externally set assignment'],
    'a level social care': ['Portfolio', 'Externally set assignment'],
    'a level early years': ['Portfolio', 'Externally set assignment'],
    'a level child development': ['Portfolio', 'Externally set assignment'],
    'a level education': ['Portfolio', 'Externally set assignment'],
    'a level teaching': ['Portfolio', 'Externally set assignment'],
    'a level training': ['Portfolio', 'Externally set assignment'],
    'a level coaching': ['Portfolio', 'Externally set assignment'],
    'a level mentoring': ['Portfolio', 'Externally set assignment'],
    'a level counselling': ['Portfolio', 'Externally set assignment'],
    'a level psychology (a level)': ['Social influence', 'Memory', 'Attachment', 'Psychopathology', 'Approaches in psychology', 'Biopsychology', 'Research methods', 'Issues and debates in psychology'],
    'a level sociology (a level)': ['Education with theory and methods', 'Families and households', 'Beliefs in society', 'Crime and deviance', 'Theory and methods'],
    'a level business (a level)': ['What is business?', 'Managers, leadership and decision making', 'Decision making to improve marketing performance', 'Decision making to improve operational performance', 'Decision making to improve financial performance', 'Decision making to improve human resource performance', 'Analysing the strategic position of a business', 'Choosing strategic direction', 'Strategic methods: how to pursue strategies', 'Managing strategic change'],
    'a level computer science (a level)': ['Fundamentals of programming', 'Fundamentals of data structures', 'Fundamentals of algorithms', 'Theory of computation', 'Fundamentals of data representation', 'Fundamentals of computer systems', 'Fundamentals of computer organisation and architecture', 'Consequences of uses of computing', 'Fundamentals of communication and networking', 'Fundamentals of databases', 'Big Data', 'Fundamentals of functional programming', 'Systematic approach to problem solving'],
    'a level law (a level)': ['The nature of law and the English legal system', 'Criminal law', 'Tort law', 'Law of contract', 'Human rights law'],
    'a level politics (a level)': ['Government and politics of the UK', 'Government and politics of the USA', 'Political ideas'],
    'a level philosophy (a level)': ['Epistemology', 'Moral philosophy', 'Metaphysics of God', 'Metaphysics of mind'],
    'a level religious studies (a level)': ['Philosophy of religion', 'Religion and ethics', 'Study of religion'],
    'a level music (a level)': ['Performing', 'Composing', 'Appraising'],
    'a level art (a level)': ['Personal investigation', 'Externally set assignment'],
    'a level drama (a level)': ['Devising', 'Text in performance', 'Theatre makers in practice'],
    'a level media studies (a level)': ['Media language', 'Media representation', 'Media industries', 'Media audiences'],
    'a level physical education (a level)': ['Applied anatomy and physiology', 'Skill acquisition', 'Sport and society', 'Exercise physiology', 'Biomechanical movement', 'Sport psychology'],
    'a level food science (a level)': ['Food science and nutrition', 'Food safety', 'Food choice'],
    'a level textiles (a level)': ['Fibres and fabrics', 'Textile construction', 'Textile design'],
    'a level product design (a level)': ['Materials and components', 'Design and market influences', 'Processes and manufacture'],
    'a level engineering (a level)': ['Engineering principles', 'Design and manufacture', 'Systems and control'],
    'a level environmental science (a level)': ['The living environment', 'The physical environment', 'Energy resources', 'Pollution', 'Biological resources', 'Sustainability'],
    'a level geology (a level)': ['Elements, minerals and rocks', 'Surface and internal processes', 'Geological time', 'Geological hazards'],
    'a level astronomy (a level)': ['Planetary systems', 'Stars', 'Galaxies', 'Cosmology'],
    'a level classical civilisation (a level)': ['The world of the hero', 'Greek theatre', 'Roman civilisation'],
    'a level ancient history (a level)': ['Greek history', 'Roman history'],
    'a level archaeology (a level)': ['The archaeology of the British Isles', 'The archaeology of the classical world'],
    'a level history of art (a level)': ['Visual analysis', 'Themes in art', 'Art in context'],
    'a level dance (a level)': ['Performance', 'Choreography', 'Appreciation'],
    'a level film studies (a level)': ['Film form', 'Film meaning', 'Film context'],
    'a level photography (a level)': ['Portfolio', 'Externally set assignment'],
    'a level graphic communication (a level)': ['Portfolio', 'Externally set assignment'],
    'a level three-dimensional design (a level)': ['Portfolio', 'Externally set assignment'],
    'a level fine art (a level)': ['Portfolio', 'Externally set assignment'],
    'a level critical and contextual studies (a level)': ['Portfolio', 'Externally set assignment'],
    'a level digital media (a level)': ['Portfolio', 'Externally set assignment'],
    'a level moving image (a level)': ['Portfolio', 'Externally set assignment'],
    'a level sound (a level)': ['Portfolio', 'Externally set assignment'],
    'a level interactive media (a level)': ['Portfolio', 'Externally set assignment'],
    'a level games design (a level)': ['Portfolio', 'Externally set assignment'],
    'a level animation (a level)': ['Portfolio', 'Externally set assignment'],
    'a level visual effects (a level)': ['Portfolio', 'Externally set assignment'],
    'a level virtual reality (a level)': ['Portfolio', 'Externally set assignment'],
    'a level augmented reality (a level)': ['Portfolio', 'Externally set assignment'],
    'a level artificial intelligence (a level)': ['Portfolio', 'Externally set assignment'],
    'a level machine learning (a level)': ['Portfolio', 'Externally set assignment'],
    'a level data science (a level)': ['Portfolio', 'Externally set assignment'],
    'a level cyber security (a level)': ['Portfolio', 'Externally set assignment'],
    'a level ethical hacking (a level)': ['Portfolio', 'Externally set assignment'],
    'a level digital forensics (a level)': ['Portfolio', 'Externally set assignment'],
    'a level network security (a level)': ['Portfolio', 'Externally set assignment'],
    'a level cloud computing (a level)': ['Portfolio', 'Externally set assignment'],
    'a level web development (a level)': ['Portfolio', 'Externally set assignment'],
    'a level mobile app development (a level)': ['Portfolio', 'Externally set assignment'],
    'a level software engineering (a level)': ['Portfolio', 'Externally set assignment'],
    'a level systems analysis (a level)': ['Portfolio', 'Externally set assignment'],
    'a level database design (a level)': ['Portfolio', 'Externally set assignment'],
    'a level user experience design (a level)': ['Portfolio', 'Externally set assignment'],
    'a level user interface design (a level)': ['Portfolio', 'Externally set assignment'],
    'a level information technology (a level)': ['Portfolio', 'Externally set assignment'],
    'a level computing (a level)': ['Portfolio', 'Externally set assignment'],
    'a level ict (a level)': ['Portfolio', 'Externally set assignment'],
    'a level digital technology (a level)': ['Portfolio', 'Externally set assignment'],
    'a level creative media (a level)': ['Portfolio', 'Externally set assignment'],
    'a level media production (a level)': ['Portfolio', 'Externally set assignment'],
    'a level journalism (a level)': ['Portfolio', 'Externally set assignment'],
    'a level publishing (a level)': ['Portfolio', 'Externally set assignment'],
    'a level advertising (a level)': ['Portfolio', 'Externally set assignment'],
    'a level marketing (a level)': ['Portfolio', 'Externally set assignment'],
    'a level public relations (a level)': ['Portfolio', 'Externally set assignment'],
    'a level event management (a level)': ['Portfolio', 'Externally set assignment'],
    'a level hospitality (a level)': ['Portfolio', 'Externally set assignment'],
    'a level tourism (a level)': ['Portfolio', 'Externally set assignment'],
    'a level travel (a level)': ['Portfolio', 'Externally set assignment'],
    'a level leisure (a level)': ['Portfolio', 'Externally set assignment'],
    'a level sport (a level)': ['Portfolio', 'Externally set assignment'],
    'a level exercise science (a level)': ['Portfolio', 'Externally set assignment'],
    'a level nutrition (a level)': ['Portfolio', 'Externally set assignment'],
    'a level health (a level)': ['Portfolio', 'Externally set assignment'],
    'a level social care (a level)': ['Portfolio', 'Externally set assignment'],
    'a level early years (a level)': ['Portfolio', 'Externally set assignment'],
    'a level child development (a level)': ['Portfolio', 'Externally set assignment'],
    'a level education (a level)': ['Portfolio', 'Externally set assignment'],
    'a level teaching (a level)': ['Portfolio', 'Externally set assignment'],
    'a level training (a level)': ['Portfolio', 'Externally set assignment'],
    'a level coaching (a level)': ['Portfolio', 'Externally set assignment'],
    'a level mentoring (a level)': ['Portfolio', 'Externally set assignment'],
    'a level counselling (a level)': ['Portfolio', 'Externally set assignment']
  };
  const keys = Object.keys(syllabus);
  for (const key of keys) {
    if (normalized.includes(key) || key.includes(normalized)) {
      return syllabus[key];
    }
  }
  return [];
}
module.exports = { autoDetectExamSyllabus };